title: tutoriel.dev
description: Tutoriels en programmation, bases de données, administration systèmes

url: https://tutoriel.dev
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Accueil
    url: /index.html
  - title: Apropos de nous
    url: /apropos-de-tutoriel-dev
  - title: Contact
    url: /contact

social:
  github: trash07
  twitter: lkpeto
  facebook: brianmaierjr
  email: mmkpeto5@gmail.com
  linkedin: lkpeto

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
