apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tutoriel-dev-ingress
  labels:
    name: tutoriel-dev-ingress
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: tutoriel.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tutoriel-dev-service
            port: 
              number: 80
  tls:
  - hosts:
    - tutoriel.dev
    secretName: turoriel-dev-cert
