apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tutoriel-dev-ingress
  labels:
    name: tutoriel-dev-ingress
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: tutoriel.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tutoriel-dev-service
            port: 
              number: 80
