server {
    listen 80;
    server_name localhost;
    root /var/www/localhost;
    add_header X-Frame-Options "SAMEORIGIN";
    location / {
        try_files $uri $uri/ $uri/index.html /index.html =404;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}