---
- name: Download artifact
  become: false
  hosts: servers
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    remote_folder: null # provided in param
    current_directory: null # provided in param
  tasks:
    - name: Download
      ansible.builtin.fetch:
        src: '{{ remote_folder }}/artifact.tar.bz2'
        dest: '{{ current_directory }}/'
        flat: true
      register: fetch_result
    - name: Debug fetch result
      ansible.builtin.debug:
        var: |
          File saved to: {{ fetch_result.dest }}
          Original remote path: {{ fetch_result.src }}
#    - name: Extract artifact
#      ansible.builtin.unarchive:
#        src: '{{ current_directory }}/artifact.tar.bz2'
#        dest: '{{ current_directory }}'
#        remote_src: false
#        remove: true
