---
- name: Save build artifact
  become: false
  hosts: servers
  gather_facts: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  tasks:
    - name: Compress
      community.general.archive:
        path:
          - ci/
          - public/
        dest: artifact.tar.bz2
        format: bz2
    - name: Store artifact
      ansible.builtin.copy:
        src: artifact.tar.bz2
        dest: /tmp/artifact.tar.bz2
