name: 2 | Promote to RC
on:
  push:
    branches:
      - master
      - hotfix/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://${{ vars.HOST }}
    steps:
      - name: Promote to RC
        run: ls
