name: 3 | Release changes
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://${{ vars.HOST }}
    steps:
      - name: Publish changes
        run: ls
