name: 1 | Pull request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - feat/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_JS_VERSION}}
      - name: List files
        run: |
          set -x 
          npm install
          npm run build
          ls