name: 1 | Pull request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - feat/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List files
        run: ls
