name: 1 | Pull request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - feat/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_JS_VERSION }}
          cache: 'npm'
      - name: Build static site
        run: |
          set -x 
          npm install
          npm run build
      - name: Save artifact
        env:
          REMOTE_FOLDER: '/home/github/dev/artifact/${{ github.repository }}/pull-request'
        run: |
          set -x
          ansible-playbook -i ci/ansible/inventory.ini \
            ci/ansible/playbooks/save-artifact.yml \
            --extra-vars="ansible_user=${{ secrets.ANSIBLE_USER }} ansible_password=${{ secrets.ANSIBLE_PASS }} current_directory=$(pwd) \
            remote_folder=${REMOTE_FOLDER}"

  deploy-to-preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to preview environment
        env:
          REMOTE_FOLDER: '/home/github/dev/artifact/${{ github.repository }}/pull-request'
        run: |
          set -x
          ls -l
